"""Add app user model

Revision ID: 31a2f3618543
Revises: 01e087a6f333
Create Date: 2025-02-09 14:45:16.371735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31a2f3618543'
down_revision: Union[str, None] = '01e087a6f333'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_users_id'), 'app_users', ['id'], unique=False)
    op.create_index(op.f('ix_app_users_phone'), 'app_users', ['phone'], unique=True)
    op.add_column('activities', sa.Column('organizer_id', sa.Integer(), nullable=True))
    op.drop_constraint('activities_creator_id_fkey', 'activities', type_='foreignkey')
    op.create_foreign_key(None, 'activities', 'users', ['organizer_id'], ['id'])
    op.drop_column('activities', 'creator_id')
    op.add_column('activity_participants', sa.Column('joined_at', sa.DateTime(), nullable=True))
    op.add_column('guides', sa.Column('author_id', sa.Integer(), nullable=True))
    op.drop_constraint('guides_creator_id_fkey', 'guides', type_='foreignkey')
    op.create_foreign_key(None, 'guides', 'users', ['author_id'], ['id'])
    op.drop_column('guides', 'creator_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guides', sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'guides', type_='foreignkey')
    op.create_foreign_key('guides_creator_id_fkey', 'guides', 'users', ['creator_id'], ['id'])
    op.drop_column('guides', 'author_id')
    op.drop_column('activity_participants', 'joined_at')
    op.add_column('activities', sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.create_foreign_key('activities_creator_id_fkey', 'activities', 'users', ['creator_id'], ['id'])
    op.drop_column('activities', 'organizer_id')
    op.drop_index(op.f('ix_app_users_phone'), table_name='app_users')
    op.drop_index(op.f('ix_app_users_id'), table_name='app_users')
    op.drop_table('app_users')
    # ### end Alembic commands ###
