"""Update pet model

Revision ID: 605af3f1bd33
Revises: 90ed2c6d4164
Create Date: 2025-02-09 01:02:32.113713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '605af3f1bd33'
down_revision: Union[str, None] = '90ed2c6d4164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet_interactions', sa.Column('type', sa.String(), nullable=True))
    op.add_column('pet_interactions', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('pet_interactions', sa.Column('health_effect', sa.Integer(), nullable=True))
    op.add_column('pet_interactions', sa.Column('happiness_effect', sa.Integer(), nullable=True))
    op.add_column('pet_interactions', sa.Column('experience_gain', sa.Integer(), nullable=True))
    op.drop_column('pet_interactions', 'interaction_type')
    op.drop_column('pet_interactions', 'happiness_change')
    op.drop_column('pet_interactions', 'timestamp')
    op.drop_column('pet_interactions', 'health_change')
    op.drop_column('pet_interactions', 'energy_change')
    op.add_column('pets', sa.Column('breed', sa.String(), nullable=True))
    op.add_column('pets', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('pets', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('pets', sa.Column('experience', sa.Integer(), nullable=True))
    op.alter_column('pets', 'type',
               existing_type=postgresql.ENUM('CAT', 'DOG', 'BIRD', 'RABBIT', name='pettype'),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('pets', 'energy')
    op.drop_column('pets', 'last_interaction')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('last_interaction', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('pets', sa.Column('energy', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('pets', 'type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('CAT', 'DOG', 'BIRD', 'RABBIT', name='pettype'),
               existing_nullable=True)
    op.drop_column('pets', 'experience')
    op.drop_column('pets', 'description')
    op.drop_column('pets', 'age')
    op.drop_column('pets', 'breed')
    op.add_column('pet_interactions', sa.Column('energy_change', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('pet_interactions', sa.Column('health_change', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('pet_interactions', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('pet_interactions', sa.Column('happiness_change', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('pet_interactions', sa.Column('interaction_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('pet_interactions', 'experience_gain')
    op.drop_column('pet_interactions', 'happiness_effect')
    op.drop_column('pet_interactions', 'health_effect')
    op.drop_column('pet_interactions', 'description')
    op.drop_column('pet_interactions', 'type')
    # ### end Alembic commands ###
